name: (HACK) Run App on Actions

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t gaokao-advisor .

      - name: Download and setup ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install ngrok

      - name: Authenticate ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Run Docker container and expose with ngrok
        env:
          # These secrets must be configured in your repository settings
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          LOAD_ENROLLMENT_DATA: "true"
          PORT: 5000
        run: |
          # Run the Docker container in detached mode
          # We pass the secrets as environment variables to the container
          docker run -d --name gaokao-app \
            -e PORT=${PORT} \
            -e OPENAI_API_KEY=${OPENAI_API_KEY} \
            -e OPENAI_API_BASE=${OPENAI_API_BASE} \
            -e REDIS_URL=${REDIS_URL} \
            -e LOAD_ENROLLMENT_DATA=${LOAD_ENROLLMENT_DATA} \
            -p ${PORT}:${PORT} \
            gaokao-advisor

          # Wait a few seconds for the container to start
          sleep 10

          # Start ngrok tunnel to expose the container's port
          ngrok http ${PORT} --log=stdout > ngrok.log &
          sleep 5

          # Extract the public URL from the ngrok log and print it
          echo "----------------------------------------------------------------"
          echo "Your temporary URL is:"
          grep -o 'url=https://[a-zA-Z0-9.-]*\.ngrok-free\.app' ngrok.log | sed 's/url=//'
          echo "----------------------------------------------------------------"
          echo "NOTE: This job will be terminated after a few hours."
          echo "This is NOT a real hosting solution."
          # Keep the job alive
          sleep 21000 # Keep alive for just under 6 hours